[package]
name = "swc_ts_dts"
version = "0.1.0"
authors = ["강동윤 <kdy1997l.dev@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
