[package]
name = "swc_ts_dts"
version = "0.1.0"
authors = ["강동윤 <kdy1997l.dev@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
swc_common = { path = "../../common" }
swc_ecma_ast = { path = "../../ecmascript/ast" }
swc_ts_checker = { path = "../checker" }